version: 2.1
orbs:
  puppeteer: threetreeslight/puppeteer@0.1.2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - js-dependencies-{{ checksum "package.json" }}
            - js-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: js-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm run build:test
      - run: npm test